laika:
    build: .
    command: go run main.go
    links:
        - mysql
    ports:
        - "8000:8000"
    environment:
        LAIKA_MYSQL_HOST: mysql
        LAIKA_MYSQL_PORT: 3306
        LAIKA_MYSQL_USERNAME: root
        LAIKA_MYSQL_PASSWORD: root
        LAIKA_MYSQL_DBNAME: laika
        LAIKA_STATSD_HOST: localhost
        LAIKA_STATSD_PORT: 8125
    volumes:
        - ./:/go/src/github.com/MEDIGO/laika

mysql:
    image: mysql:5
    ports:
        - "3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: laika
