version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1
    working_directory: /go/src/github.com/MEDIGO/laika
    steps:
      - checkout
      - run: go mod download
      - run: touch .env
      - run: pwd
      - run: ls
      - run: make install
      - run: make build
      - run: make report
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make image
      - run: make publish
